//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Zero_HungerEntities3 : DbContext
    {
        public Zero_HungerEntities3()
            : base("name=Zero_HungerEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CollectRequest> CollectRequests { get; set; }
        public virtual DbSet<DistributionRecord> DistributionRecords { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<Restaurent> Restaurents { get; set; }
        public virtual DbSet<FoodItem> FoodItems { get; set; }
    }
}
